### ISSUE TITLE
Version pinning against other projects

### ISSUE THREAD

**Issue by ghost** [TechnitiumSoftware/TechnitiumLibrary#11]
How do you handle version pinning against other projects like DNSServer? For example V13.0 was released today, how do you handle possible inconsistencies of compiling v13.0 against a possible future version of TechnitiumLibrary?

**Comment by ShreyasZare** [comment]
Thanks for asking. Older versions for a project can be compiled by taking a branch out of the Technitium Library project from a commit that matches the same release data as that of the project's version commit being compiled.

**Comment by FabianRig** [comment]
Could you perhaps consider tags / releases? That would make maintaining the nixpkgs release (of Technitium DNS Server) easier.

**Comment by ShreyasZare** [comment]
> Could you perhaps consider tags / releases? That would make maintaining the nixpkgs release (of Technitium DNS Server) easier.

Thanks for the suggestion. Will start adding tags and will add one for the current release.
