### ISSUE TITLE
How to handle two firewall rules with a same name but different protocols?

### ISSUE THREAD

**Issue by YueLu0116** [TechnitiumSoftware/TechnitiumLibrary#4]
In `WindowsFirewall.cs` line 153: `public static RuleStatus RuleExistsVista(string name, string applicationPath){//...}`:
If two firewall rules with same name but different protocols, e.g., one is TCP and the other is UDP, this function possibly cannot distinguish them. If I want to check a rule's existence (UDP protocol), but another rule which has the same name but is under TCP protocol exists, can this function success?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I have just updated the code to allow specifying optional protocol to check the rule status. Do take a look [here](https://github.com/TechnitiumSoftware/TechnitiumLibrary/blob/master/TechnitiumLibrary.Net.Firewall/WindowsFirewall.cs#L154) and let me know if that works for you.

**Comment by YueLu0116** [comment]
> Thanks for the feedback. I have just updated the code to allow specifying optional protocol to check the rule status. Do take a look [here](https://github.com/TechnitiumSoftware/TechnitiumLibrary/blob/master/TechnitiumLibrary.Net.Firewall/WindowsFirewall.cs#L154) and let me know if that works for you.

Thanks for your updating. It can work
