### ISSUE TITLE
Possible copy-paste bug

### ISSUE THREAD

**Issue by Singijeon** [TechnitiumSoftware/TechnitiumLibrary#8]
I think `question` variable reference in last added piece should be replaced by `q` like in old part of code:
https://github.com/TechnitiumSoftware/TechnitiumLibrary/blob/122de25306cf538c25b5807184012928dfc6a7b8/TechnitiumLibrary.Net/Dns/DnsClient.cs#L4530-L4560

**Comment by ShreyasZare** [comment]
Thanks for reporting that. Will get it fixed.

**Comment by ShreyasZare** [comment]
This issue was fixed in the earlier release.
